// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TestData.proto

package de.hszemi.sensorid;

public final class TestData {
  private TestData() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface FeatureVectorOrBuilder extends
      // @@protoc_insertion_point(interface_extends:sensorid.FeatureVector)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string sensortype = 1;</code>
     */
    boolean hasSensortype();
    /**
     * <code>required string sensortype = 1;</code>
     */
    java.lang.String getSensortype();
    /**
     * <code>required string sensortype = 1;</code>
     */
    com.google.protobuf.ByteString
        getSensortypeBytes();

    /**
     * <code>required string sensorname = 2;</code>
     */
    boolean hasSensorname();
    /**
     * <code>required string sensorname = 2;</code>
     */
    java.lang.String getSensorname();
    /**
     * <code>required string sensorname = 2;</code>
     */
    com.google.protobuf.ByteString
        getSensornameBytes();

    /**
     * <code>repeated double features = 3;</code>
     */
    java.util.List<java.lang.Double> getFeaturesList();
    /**
     * <code>repeated double features = 3;</code>
     */
    int getFeaturesCount();
    /**
     * <code>repeated double features = 3;</code>
     */
    double getFeatures(int index);
  }
  /**
   * Protobuf type {@code sensorid.FeatureVector}
   */
  public static final class FeatureVector extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:sensorid.FeatureVector)
      FeatureVectorOrBuilder {
    // Use FeatureVector.newBuilder() to construct.
    private FeatureVector(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private FeatureVector(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final FeatureVector defaultInstance;
    public static FeatureVector getDefaultInstance() {
      return defaultInstance;
    }

    public FeatureVector getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private FeatureVector(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              sensortype_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              sensorname_ = bs;
              break;
            }
            case 25: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                features_ = new java.util.ArrayList<java.lang.Double>();
                mutable_bitField0_ |= 0x00000004;
              }
              features_.add(input.readDouble());
              break;
            }
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004) && input.getBytesUntilLimit() > 0) {
                features_ = new java.util.ArrayList<java.lang.Double>();
                mutable_bitField0_ |= 0x00000004;
              }
              while (input.getBytesUntilLimit() > 0) {
                features_.add(input.readDouble());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          features_ = java.util.Collections.unmodifiableList(features_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.hszemi.sensorid.TestData.internal_static_sensorid_FeatureVector_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.hszemi.sensorid.TestData.internal_static_sensorid_FeatureVector_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              de.hszemi.sensorid.TestData.FeatureVector.class, de.hszemi.sensorid.TestData.FeatureVector.Builder.class);
    }

    public static com.google.protobuf.Parser<FeatureVector> PARSER =
        new com.google.protobuf.AbstractParser<FeatureVector>() {
      public FeatureVector parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FeatureVector(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<FeatureVector> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int SENSORTYPE_FIELD_NUMBER = 1;
    private java.lang.Object sensortype_;
    /**
     * <code>required string sensortype = 1;</code>
     */
    public boolean hasSensortype() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string sensortype = 1;</code>
     */
    public java.lang.String getSensortype() {
      java.lang.Object ref = sensortype_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sensortype_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string sensortype = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSensortypeBytes() {
      java.lang.Object ref = sensortype_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sensortype_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENSORNAME_FIELD_NUMBER = 2;
    private java.lang.Object sensorname_;
    /**
     * <code>required string sensorname = 2;</code>
     */
    public boolean hasSensorname() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string sensorname = 2;</code>
     */
    public java.lang.String getSensorname() {
      java.lang.Object ref = sensorname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sensorname_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string sensorname = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSensornameBytes() {
      java.lang.Object ref = sensorname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sensorname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FEATURES_FIELD_NUMBER = 3;
    private java.util.List<java.lang.Double> features_;
    /**
     * <code>repeated double features = 3;</code>
     */
    public java.util.List<java.lang.Double>
        getFeaturesList() {
      return features_;
    }
    /**
     * <code>repeated double features = 3;</code>
     */
    public int getFeaturesCount() {
      return features_.size();
    }
    /**
     * <code>repeated double features = 3;</code>
     */
    public double getFeatures(int index) {
      return features_.get(index);
    }

    private void initFields() {
      sensortype_ = "";
      sensorname_ = "";
      features_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasSensortype()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSensorname()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getSensortypeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getSensornameBytes());
      }
      for (int i = 0; i < features_.size(); i++) {
        output.writeDouble(3, features_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getSensortypeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getSensornameBytes());
      }
      {
        int dataSize = 0;
        dataSize = 8 * getFeaturesList().size();
        size += dataSize;
        size += 1 * getFeaturesList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static de.hszemi.sensorid.TestData.FeatureVector parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.hszemi.sensorid.TestData.FeatureVector parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.hszemi.sensorid.TestData.FeatureVector parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.hszemi.sensorid.TestData.FeatureVector parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.hszemi.sensorid.TestData.FeatureVector parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static de.hszemi.sensorid.TestData.FeatureVector parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static de.hszemi.sensorid.TestData.FeatureVector parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static de.hszemi.sensorid.TestData.FeatureVector parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static de.hszemi.sensorid.TestData.FeatureVector parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static de.hszemi.sensorid.TestData.FeatureVector parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(de.hszemi.sensorid.TestData.FeatureVector prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code sensorid.FeatureVector}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:sensorid.FeatureVector)
        de.hszemi.sensorid.TestData.FeatureVectorOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return de.hszemi.sensorid.TestData.internal_static_sensorid_FeatureVector_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return de.hszemi.sensorid.TestData.internal_static_sensorid_FeatureVector_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                de.hszemi.sensorid.TestData.FeatureVector.class, de.hszemi.sensorid.TestData.FeatureVector.Builder.class);
      }

      // Construct using de.hszemi.sensorid.TestData.FeatureVector.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        sensortype_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        sensorname_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        features_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.hszemi.sensorid.TestData.internal_static_sensorid_FeatureVector_descriptor;
      }

      public de.hszemi.sensorid.TestData.FeatureVector getDefaultInstanceForType() {
        return de.hszemi.sensorid.TestData.FeatureVector.getDefaultInstance();
      }

      public de.hszemi.sensorid.TestData.FeatureVector build() {
        de.hszemi.sensorid.TestData.FeatureVector result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public de.hszemi.sensorid.TestData.FeatureVector buildPartial() {
        de.hszemi.sensorid.TestData.FeatureVector result = new de.hszemi.sensorid.TestData.FeatureVector(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.sensortype_ = sensortype_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sensorname_ = sensorname_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          features_ = java.util.Collections.unmodifiableList(features_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.features_ = features_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.hszemi.sensorid.TestData.FeatureVector) {
          return mergeFrom((de.hszemi.sensorid.TestData.FeatureVector)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(de.hszemi.sensorid.TestData.FeatureVector other) {
        if (other == de.hszemi.sensorid.TestData.FeatureVector.getDefaultInstance()) return this;
        if (other.hasSensortype()) {
          bitField0_ |= 0x00000001;
          sensortype_ = other.sensortype_;
          onChanged();
        }
        if (other.hasSensorname()) {
          bitField0_ |= 0x00000002;
          sensorname_ = other.sensorname_;
          onChanged();
        }
        if (!other.features_.isEmpty()) {
          if (features_.isEmpty()) {
            features_ = other.features_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureFeaturesIsMutable();
            features_.addAll(other.features_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSensortype()) {
          
          return false;
        }
        if (!hasSensorname()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        de.hszemi.sensorid.TestData.FeatureVector parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (de.hszemi.sensorid.TestData.FeatureVector) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object sensortype_ = "";
      /**
       * <code>required string sensortype = 1;</code>
       */
      public boolean hasSensortype() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string sensortype = 1;</code>
       */
      public java.lang.String getSensortype() {
        java.lang.Object ref = sensortype_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            sensortype_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string sensortype = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSensortypeBytes() {
        java.lang.Object ref = sensortype_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sensortype_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string sensortype = 1;</code>
       */
      public Builder setSensortype(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        sensortype_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string sensortype = 1;</code>
       */
      public Builder clearSensortype() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sensortype_ = getDefaultInstance().getSensortype();
        onChanged();
        return this;
      }
      /**
       * <code>required string sensortype = 1;</code>
       */
      public Builder setSensortypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        sensortype_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object sensorname_ = "";
      /**
       * <code>required string sensorname = 2;</code>
       */
      public boolean hasSensorname() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string sensorname = 2;</code>
       */
      public java.lang.String getSensorname() {
        java.lang.Object ref = sensorname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            sensorname_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string sensorname = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSensornameBytes() {
        java.lang.Object ref = sensorname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sensorname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string sensorname = 2;</code>
       */
      public Builder setSensorname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        sensorname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string sensorname = 2;</code>
       */
      public Builder clearSensorname() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sensorname_ = getDefaultInstance().getSensorname();
        onChanged();
        return this;
      }
      /**
       * <code>required string sensorname = 2;</code>
       */
      public Builder setSensornameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        sensorname_ = value;
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Double> features_ = java.util.Collections.emptyList();
      private void ensureFeaturesIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          features_ = new java.util.ArrayList<java.lang.Double>(features_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated double features = 3;</code>
       */
      public java.util.List<java.lang.Double>
          getFeaturesList() {
        return java.util.Collections.unmodifiableList(features_);
      }
      /**
       * <code>repeated double features = 3;</code>
       */
      public int getFeaturesCount() {
        return features_.size();
      }
      /**
       * <code>repeated double features = 3;</code>
       */
      public double getFeatures(int index) {
        return features_.get(index);
      }
      /**
       * <code>repeated double features = 3;</code>
       */
      public Builder setFeatures(
          int index, double value) {
        ensureFeaturesIsMutable();
        features_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double features = 3;</code>
       */
      public Builder addFeatures(double value) {
        ensureFeaturesIsMutable();
        features_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double features = 3;</code>
       */
      public Builder addAllFeatures(
          java.lang.Iterable<? extends java.lang.Double> values) {
        ensureFeaturesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, features_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double features = 3;</code>
       */
      public Builder clearFeatures() {
        features_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:sensorid.FeatureVector)
    }

    static {
      defaultInstance = new FeatureVector(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:sensorid.FeatureVector)
  }

  public interface TestResultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:sensorid.TestResult)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string result_displayname = 1;</code>
     */
    boolean hasResultDisplayname();
    /**
     * <code>required string result_displayname = 1;</code>
     */
    java.lang.String getResultDisplayname();
    /**
     * <code>required string result_displayname = 1;</code>
     */
    com.google.protobuf.ByteString
        getResultDisplaynameBytes();
  }
  /**
   * Protobuf type {@code sensorid.TestResult}
   */
  public static final class TestResult extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:sensorid.TestResult)
      TestResultOrBuilder {
    // Use TestResult.newBuilder() to construct.
    private TestResult(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TestResult(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TestResult defaultInstance;
    public static TestResult getDefaultInstance() {
      return defaultInstance;
    }

    public TestResult getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TestResult(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              resultDisplayname_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.hszemi.sensorid.TestData.internal_static_sensorid_TestResult_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.hszemi.sensorid.TestData.internal_static_sensorid_TestResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              de.hszemi.sensorid.TestData.TestResult.class, de.hszemi.sensorid.TestData.TestResult.Builder.class);
    }

    public static com.google.protobuf.Parser<TestResult> PARSER =
        new com.google.protobuf.AbstractParser<TestResult>() {
      public TestResult parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TestResult(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TestResult> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int RESULT_DISPLAYNAME_FIELD_NUMBER = 1;
    private java.lang.Object resultDisplayname_;
    /**
     * <code>required string result_displayname = 1;</code>
     */
    public boolean hasResultDisplayname() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string result_displayname = 1;</code>
     */
    public java.lang.String getResultDisplayname() {
      java.lang.Object ref = resultDisplayname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          resultDisplayname_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string result_displayname = 1;</code>
     */
    public com.google.protobuf.ByteString
        getResultDisplaynameBytes() {
      java.lang.Object ref = resultDisplayname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resultDisplayname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      resultDisplayname_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasResultDisplayname()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getResultDisplaynameBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getResultDisplaynameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static de.hszemi.sensorid.TestData.TestResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.hszemi.sensorid.TestData.TestResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.hszemi.sensorid.TestData.TestResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.hszemi.sensorid.TestData.TestResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.hszemi.sensorid.TestData.TestResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static de.hszemi.sensorid.TestData.TestResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static de.hszemi.sensorid.TestData.TestResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static de.hszemi.sensorid.TestData.TestResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static de.hszemi.sensorid.TestData.TestResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static de.hszemi.sensorid.TestData.TestResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(de.hszemi.sensorid.TestData.TestResult prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code sensorid.TestResult}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:sensorid.TestResult)
        de.hszemi.sensorid.TestData.TestResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return de.hszemi.sensorid.TestData.internal_static_sensorid_TestResult_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return de.hszemi.sensorid.TestData.internal_static_sensorid_TestResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                de.hszemi.sensorid.TestData.TestResult.class, de.hszemi.sensorid.TestData.TestResult.Builder.class);
      }

      // Construct using de.hszemi.sensorid.TestData.TestResult.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        resultDisplayname_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.hszemi.sensorid.TestData.internal_static_sensorid_TestResult_descriptor;
      }

      public de.hszemi.sensorid.TestData.TestResult getDefaultInstanceForType() {
        return de.hszemi.sensorid.TestData.TestResult.getDefaultInstance();
      }

      public de.hszemi.sensorid.TestData.TestResult build() {
        de.hszemi.sensorid.TestData.TestResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public de.hszemi.sensorid.TestData.TestResult buildPartial() {
        de.hszemi.sensorid.TestData.TestResult result = new de.hszemi.sensorid.TestData.TestResult(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.resultDisplayname_ = resultDisplayname_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.hszemi.sensorid.TestData.TestResult) {
          return mergeFrom((de.hszemi.sensorid.TestData.TestResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(de.hszemi.sensorid.TestData.TestResult other) {
        if (other == de.hszemi.sensorid.TestData.TestResult.getDefaultInstance()) return this;
        if (other.hasResultDisplayname()) {
          bitField0_ |= 0x00000001;
          resultDisplayname_ = other.resultDisplayname_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasResultDisplayname()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        de.hszemi.sensorid.TestData.TestResult parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (de.hszemi.sensorid.TestData.TestResult) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object resultDisplayname_ = "";
      /**
       * <code>required string result_displayname = 1;</code>
       */
      public boolean hasResultDisplayname() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string result_displayname = 1;</code>
       */
      public java.lang.String getResultDisplayname() {
        java.lang.Object ref = resultDisplayname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            resultDisplayname_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string result_displayname = 1;</code>
       */
      public com.google.protobuf.ByteString
          getResultDisplaynameBytes() {
        java.lang.Object ref = resultDisplayname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          resultDisplayname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string result_displayname = 1;</code>
       */
      public Builder setResultDisplayname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        resultDisplayname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string result_displayname = 1;</code>
       */
      public Builder clearResultDisplayname() {
        bitField0_ = (bitField0_ & ~0x00000001);
        resultDisplayname_ = getDefaultInstance().getResultDisplayname();
        onChanged();
        return this;
      }
      /**
       * <code>required string result_displayname = 1;</code>
       */
      public Builder setResultDisplaynameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        resultDisplayname_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:sensorid.TestResult)
    }

    static {
      defaultInstance = new TestResult(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:sensorid.TestResult)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sensorid_FeatureVector_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sensorid_FeatureVector_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sensorid_TestResult_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sensorid_TestResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016TestData.proto\022\010sensorid\"I\n\rFeatureVec" +
      "tor\022\022\n\nsensortype\030\001 \002(\t\022\022\n\nsensorname\030\002 " +
      "\002(\t\022\020\n\010features\030\003 \003(\001\"(\n\nTestResult\022\032\n\022r" +
      "esult_displayname\030\001 \002(\tB\024\n\022de.hszemi.sen" +
      "sorid"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_sensorid_FeatureVector_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_sensorid_FeatureVector_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_sensorid_FeatureVector_descriptor,
        new java.lang.String[] { "Sensortype", "Sensorname", "Features", });
    internal_static_sensorid_TestResult_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_sensorid_TestResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_sensorid_TestResult_descriptor,
        new java.lang.String[] { "ResultDisplayname", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
